### ISSUE TITLE
What theme is used in your screenshots?

### ISSUE THREAD

**Issue by ZeanArts** [Fooxly/themeswitch#3]
Hi,
nice Extension!
One question though: What dark and white theme are you using in this screenshot/gif?

![image](https://user-images.githubusercontent.com/13322998/105176850-1be7e800-5b26-11eb-9fb9-f385ee07416f.png)

(Not sure if it is the right way to ask this via an issue)

**Comment by thom1606** [comment]
We use the following themes (any themes will work)

Dark Mode: One Dark Pro
Light Mode: Atom One Light
